name: Links on live

on: pull_request

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Install linkchecker
        # As soon as version 10 is released we should replace this:
        run: sudo apt install linkchecker

      - name: Run linkchecker
        run: linkchecker --check-extern --threads 0 --ignore-url '.*&start=.*' --ignore-url 'https://ubuntuforums.org' --ignore-url 'https://res.cloudinary.com' --ignore-url /q_auto --ignore-url /fl_sanitize --ignore-url /w_* --ignore-url /h_* --ignore-url '/blog/*' --no-warnings https://ubuntu.com --output csv > links-report.csv || true

      - name: Update Google Spreadsheet
        uses: canonical-web-and-design/csv-to-google-spreadsheet@stable
        with:
          csv_path: links-report.csv
          spreadsheet_id: ${{ secrets.google_spreadsheet_id_linkchecker }}
          worksheet: 0
          google_service_account_email: ${{ secrets.google_service_account_email }}
          google_service_account_private_key: ${{ secrets.google_service_account_private_key }}
